### ISSUE TITLE
Non-default port in .ssh/config

### ISSUE THREAD

**Issue by justinsb** [loft-sh/devpod-provider-ssh#10]
I have an SSH server that is (only) in my \~/.ssh/config, like this:

```
Host myserver
  HostName 10.20.30.40
  Port 10022
  User myuser
```

So a non-default port, and a hostname that does not actually resolve via DNS or /etc/hosts.

devpod-provider-ssh provider *is* able to connect to the host IP, because `ssh myserver` understands \~/.ssh/config.  However, I believe that devpod-provider-ssh passes  `-p 22` even when I haven't specified the port via the `PORT` config value.  Flags override the values in \~/.ssh/config, so ssh tries to connect on the wrong port.

A fix could be to change it so that the default is not specified in provider.yaml, and we keep track of whether the port is explicitly specified or not, and we only pass `-p 22` if `PORT` is explicitly specified.

I did find a workaround, which is to specify PORT explicitly with something like: `devpod provider set-options -o PORT=10022`

**Comment by 89luca89** [comment]
Hi @justinsb thanks for the issue! I'll take a look at this :+1:

**Comment by 89luca89** [comment]
This will be included in the next release :+1:

**Comment by justinsb** [comment]
Awesome, thank you @89luca89 !
