### ISSUE TITLE
`EXTRA_FLAGS` option is ineffective

### ISSUE THREAD

**Issue by maxbrunet** [loft-sh/devpod-provider-ssh#12]
`EXTRA_FLAGS` is not read here, thus the option is ineffective at the moment:

https://github.com/loft-sh/devpod-provider-ssh/blob/d5c8c344f08b29fce72acc78876dd56aeaadd1da/pkg/options/options.go#L35-L61

This also looks like dead code:

https://github.com/loft-sh/devpod-provider-ssh/blob/d5c8c344f08b29fce72acc78876dd56aeaadd1da/pkg/options/options.go#L25-L33

**Comment by FabianKramm** [comment]
@maxbrunet thanks for creating this issue! Oh yes that seems like an error
