### ISSUE TITLE
Spliting of extra flags is too naive

### ISSUE THREAD

**Issue by maxbrunet** [loft-sh/devpod-provider-ssh#13]
Splitting by spaces will not work in many cases

https://github.com/loft-sh/devpod-provider-ssh/blob/d5c8c344f08b29fce72acc78876dd56aeaadd1da/pkg/ssh/ssh.go#L50

Here's an example with a `ProxyCommand` that would break:

```
EXTRA_FLAGS='-i~/.ssh/google_compute_engine -oProxyCommand="gcloud compute start-iap-tunnel %h %p --listen-on-stdin --project=<project> --zone=<region> --verbosity=warning"'
```

There are libraries out there that do "shell-like" splitting, I have not done the research to figure which one is best.

Extra note: the reproduction command in the error message is missing a space after `ssh`, it should be `"ssh "`:

https://github.com/loft-sh/devpod-provider-ssh/blob/d5c8c344f08b29fce72acc78876dd56aeaadd1da/pkg/ssh/ssh.go#L39

**Comment by FabianKramm** [comment]
@maxbrunet thanks for reporting this issue! We will fix this!
